apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: test
  name: test
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: test
spec:
  hard:
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: "10"
    requests.cpu: "2"
    requests.memory: 2Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: test
spec:
  limits:
    - default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 100m
        memory: 256Mi
      type: Container