apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: isolate-test-environment
  namespace: test
spec:
  egress:
    # 1. Allow DNS lookups to CoreDNS in kube-system
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
      to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
    # 2. Allow egress to external services and Azure MySQL subnet
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.1.0/24 # Block cross-pod traffic on the AKS internal subnet
  ingress:
    # 1. Allow intra-namespace traffic
    - from:
        - podSelector: {}
    # 2. Allow incoming traffic only from the Ingress Controller namespace
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
  podSelector: {} # Applies to all pods within the test namespace
  policyTypes:
    - Ingress
    - Egress